### ISSUE TITLE
Decide how to handle nested resources

### ISSUE THREAD

**Issue by Manfred** [Manfred/Reynard#16]
When the schema defines a property that is an object or array we need to build an object based on the response or figure out a different way to deal with it.

* Response should only be parsed / processed when `object` or other payload related methods are called.
* It should be possible to get the ‘raw’ parsed JSON response instead of an object.

**Comment by alexmalus** [comment]
Hy @Manfred . https://github.com/nedap/ons-medicatie/issues/3303 might need this issue to be done. Are you planning on working on it anytime soon?
